### ISSUE TITLE
RIO probably needs a filter method 

### ISSUE THREAD

**Issue by adefazio** [ambiata/mundane#81]
The following line of code in a for comprehension works fine:

    startT <- RIO.io(System.currentTimeMillis)

But when I add a type annotation, I get:

    [error] /Users/adefazio/projects/gremlin/gremlin-cli/src/main/scala/com/ambiata/gremlin/cli/FeaturePrepareBase.scala:60: value filter is not a member of com.ambiata.mundane.control.RIO[Long]
    [error]       startT : Long <- RIO.io(System.currentTimeMillis)

I think this is related to:
http://stackoverflow.com/questions/4380831/why-does-filter-have-to-be-defined-for-pattern-matching-in-a-for-loop-in-scala
https://issues.scala-lang.org/browse/SI-1336

**Comment by charleso** [comment]
The `map` and `flatMap` functions are defined for `Monad` in `scalaz` and we get that those for free. However, `scalaz` have intentionally not implemented the `filter` function because it doesn't make sense on `Monad`. It _does_ exist on [MonadPlus](https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/syntax/MonadPlusSyntax.scala), but `RIO` will never be able to implement that interface.

Yah Scala. :(

Back to your original code, you can do `RIO.io[Long](...)` which is what you would normally do.
